version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
executors:
  tmp-executor:
    working_directory: ~/tmp
    docker: 
      - image: circleci/node:14
jobs: 
  lint:
    executor: tmp-executor
    steps: 
      - checkout
      - run:
          name: Installing latest version of NPM
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Installing backend dependencies
          command: 'npm install node-pre-gyp rebuild --prefix backend && npm install'
      - run:
          name: Installing frontend dependencies
          command: 'npm install --prefix frontend'
      - run:
          name: Performing linting
          command: 'npm run lint'
    # TODO: Add linting commands here
  build: 
    executor: tmp-executor
    steps: 
      - checkout
      - run:
          name: Installing latest version of NPM
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Installing backend dependencies
          command: 'npm install node-pre-gyp rebuild --prefix backend && npm install'
      - run:
          name: Installing frontend dependencies
          command: 'npm install --prefix frontend'
    # TODO: Figure out why building frontend is failing (memory requirements?)
workflows:
  lint-build-deploy:
    jobs:
      # The linter can be run for every branch
      - lint
      # Before deployment, ensure that the website is building
      - build:
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          requires:
            - lint
            - build
          filters:
            branches:
              only: main
