version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
jobs: 
  build: 
    working_directory: ~/oktavian
    docker: 
      - image: circleci/node:14
    steps: 
      - checkout
      - run:
          name: Installing latest version of NPM
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Installing backend dependencies
          command: npm install node-pre-gyp rebuild --prefix backend && npm install --prefix backend
      - run:
          name: Installing frontend dependencies
          command: npm install --prefix frontend
      - run: 
          name: Building frontend
          command: npm run-script build 
workflows:
  build-lint-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main