version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
executors:
  tmp-executor:
    working_directory: ~/tmp
    docker: 
      - image: circleci/node:14
jobs: 
  lint:
    executor: tmp-executor
    steps: 
      - checkout
      - run:
          name: Installing latest version of NPM
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Fixing issues with Node GYP
          command: 'sudo node-gyp rebuild'
      - run:
          name: Installing backend dependencies
          command: 'npm install node-pre-gyp rebuild --prefix backend && npm install'
      - run:
          name: Installing frontend dependencies
          command: 'npm install --prefix frontend'
      - run:
          name: Running ESLint & Prettier
          command: 'npm run lint'
workflows:
  lint-deploy:
    jobs:
      # The linter can be run for every branch
      - lint
      # Deployment only occurs for the main branch
      - heroku/deploy-via-git:
          requires:
            - lint
          filters:
            branches:
              only: main
