version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
jobs: 
  build: 
    working_directory: ~/oktavian
    docker: 
      - image: circleci/node:14
    steps: 
      - checkout
      - run:
          name: Installing latest version of NPM
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Installing website dependencies
          command: npm install
      - run: 
          name: Building frontend
          command: npm run-script build 
workflows:
  build-lint-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main