version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
  node: circleci/node@4.2.0
workflows:
  lint-deploy:
    jobs:
      #- node/test:
      #    name: Backend lint and style check
      #    app-dir: backend
      #    run-command: lint-check
      #- node/test:
      #    name: Frontend lint and style check
      #    app-dir: frontend
      #    run-command: lint-check
      # Deployment only occurs for the main branch
      - heroku/deploy-via-git:
          requires:
            - Backend lint and style check
            - Frontend lint and style check
          filters:
            branches:
              only: main
