name: Lint checks

on:
  pull_request:
    branches:
      main

jobs:
  backend_lint_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - working-directory: backend
      run: |
        npm ci
        npm run lint-check
  frontend_lint_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - working-directory: frontend
      run: |
        npm ci
        npm run lint-check
